#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("UnitConverter.Resource", IsApplication=true)]

namespace UnitConverter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int shareDialogList = 2131034112;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_black = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_white_matte = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ButtonStates = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int info = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mic = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int share = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash = 2130837512;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070011
			public const int MyButton = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int btn_help = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int btn_share = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int btn_speak = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int helpLayout = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int tvArea = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int tvAreaUnits = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int tvExamples = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int tvLength = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int tvLengthUnits = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int tvTemperture = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int tvTempertureUnits = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int tvTime = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int tvTimeUnits = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int tvVolume = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int tvVolumeUnits = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int tvWeight = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int tvWeightUnits = 2131165197;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Help = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Splash = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int help_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int share_button = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int speak_button = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int voice_recognition_results = 2130968581;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int ButtonText = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ButtonTextSmall = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Background = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
