using System.Collections.Generic;
using ConverterFramework;

namespace ConverterFramework
{
    //takes an object and performs the calculation

    struct UnitKey
    {
        public Units fromUnit;
        public Units toUnit;
    }

    public class Calculator
    {
         
        
        
        
        private Dictionary<UnitKey, float> unitDictionary = new Dictionary<UnitKey, float>
                                                                {
                                                                    {new UnitKey{fromUnit=Units.Unknown,toUnit=Units.Unknown  } ,        0},

                                                                    //***************************AREA*******************************************
                                                                    {new UnitKey{fromUnit=Units.Acre,toUnit=Units.Hectare  } ,                0.404687F},
                                                                    {new UnitKey{fromUnit=Units.Acre,toUnit=Units.Squarefoot  } ,             43560.17844F},
                                                                    {new UnitKey{fromUnit=Units.Acre,toUnit=Units.Squaremetre  } ,            4046.873F},
                                                                    {new UnitKey{fromUnit=Units.Acre,toUnit=Units.Squarekilometre  } ,        0.004047F},
                                                                    {new UnitKey{fromUnit=Units.Acre,toUnit=Units.Squareinch  } ,             6272665.695331F},
                                                                    {new UnitKey{fromUnit=Units.Acre,toUnit=Units.Squareyard  } ,             4840.0196F},
                                                                    {new UnitKey{fromUnit=Units.Acre,toUnit=Units.Squaremile  } ,             0.001563F},

                                                                    {new UnitKey{fromUnit=Units.Hectare,toUnit=Units.Acre  } ,                2.471044F},
                                                                    {new UnitKey{fromUnit=Units.Hectare,toUnit=Units.Squarefoot  } ,          107639.1176F},
                                                                    {new UnitKey{fromUnit=Units.Hectare,toUnit=Units.Squaremetre  } ,         10000.0012F},
                                                                    {new UnitKey{fromUnit=Units.Hectare,toUnit=Units.Squarekilometre  } ,     0.01F},
                                                                    {new UnitKey{fromUnit=Units.Hectare,toUnit=Units.Squareinch  } ,          15500031.0001F},
                                                                    {new UnitKey{fromUnit=Units.Hectare,toUnit=Units.Squareyard  } ,          11959.8999F},
                                                                    {new UnitKey{fromUnit=Units.Hectare,toUnit=Units.Squaremile  } ,          0.003861F},

                                                                    {new UnitKey{fromUnit=Units.Squarefoot,toUnit=Units.Acre  } ,             0.000023F},
                                                                    {new UnitKey{fromUnit=Units.Squarefoot,toUnit=Units.Hectare  } ,          0.000009F},
                                                                    {new UnitKey{fromUnit=Units.Squarefoot,toUnit=Units.Squaremetre  } ,      0.092903F},
                                                                    {new UnitKey{fromUnit=Units.Squarefoot,toUnit=Units.Squarekilometre  } ,  0F},
                                                                    {new UnitKey{fromUnit=Units.Squarefoot,toUnit=Units.Squareinch  } ,       144F},
                                                                    {new UnitKey{fromUnit=Units.Squarefoot,toUnit=Units.Squareyard  } ,       0.111111F},
                                                                    {new UnitKey{fromUnit=Units.Squarefoot,toUnit=Units.Squaremile  } ,       0F},

                                                                    {new UnitKey{fromUnit=Units.Squaremetre,toUnit=Units.Acre  } ,             0.000247F},
                                                                    {new UnitKey{fromUnit=Units.Squaremetre,toUnit=Units.Hectare  } ,          0.0001F},
                                                                    {new UnitKey{fromUnit=Units.Squaremetre,toUnit=Units.Squarefoot  } ,       10.76391F},
                                                                    {new UnitKey{fromUnit=Units.Squaremetre,toUnit=Units.Squarekilometre  } ,  0.000001F},
                                                                    {new UnitKey{fromUnit=Units.Squaremetre,toUnit=Units.Squareinch  } ,       1550.0031F},
                                                                    {new UnitKey{fromUnit=Units.Squaremetre,toUnit=Units.Squareyard  } ,       1.19599F},
                                                                    {new UnitKey{fromUnit=Units.Squaremetre,toUnit=Units.Squaremile  } ,       0F},

                                                                    {new UnitKey{fromUnit=Units.Squarekilometre,toUnit=Units.Acre  } ,         247.1043F},
                                                                    {new UnitKey{fromUnit=Units.Squarekilometre,toUnit=Units.Hectare  } ,      100F},
                                                                    {new UnitKey{fromUnit=Units.Squarekilometre,toUnit=Units.Squarefoot  } ,   10763910.4167F},
                                                                    {new UnitKey{fromUnit=Units.Squarekilometre,toUnit=Units.Squaremetre  } ,  1000000F},
                                                                    {new UnitKey{fromUnit=Units.Squarekilometre,toUnit=Units.Squareinch  } ,   1550003100.0062F},
                                                                    {new UnitKey{fromUnit=Units.Squarekilometre,toUnit=Units.Squareyard  } ,   1195989.9891F},
                                                                    {new UnitKey{fromUnit=Units.Squarekilometre,toUnit=Units.Squaremile  } ,   0.386102F},

                                                                    {new UnitKey{fromUnit=Units.Squareinch,toUnit=Units.Acre  } ,              0F},
                                                                    {new UnitKey{fromUnit=Units.Squareinch,toUnit=Units.Hectare  } ,           0F},
                                                                    {new UnitKey{fromUnit=Units.Squareinch,toUnit=Units.Squarefoot  } ,        0.006944F},
                                                                    {new UnitKey{fromUnit=Units.Squareinch,toUnit=Units.Squaremetre  } ,       0.000645F},
                                                                    {new UnitKey{fromUnit=Units.Squareinch,toUnit=Units.Squarekilometre  } ,   0F},
                                                                    {new UnitKey{fromUnit=Units.Squareinch,toUnit=Units.Squareyard  } ,        0.000772F},
                                                                    {new UnitKey{fromUnit=Units.Squareinch,toUnit=Units.Squaremile  } ,        0F},

                                                                    {new UnitKey{fromUnit=Units.Squareyard,toUnit=Units.Acre  } ,              0.000207F},
                                                                    {new UnitKey{fromUnit=Units.Squareyard,toUnit=Units.Hectare  } ,           0.000084F},
                                                                    {new UnitKey{fromUnit=Units.Squareyard,toUnit=Units.Squarefoot  } ,        9F},
                                                                    {new UnitKey{fromUnit=Units.Squareyard,toUnit=Units.Squaremetre  } ,       0.836127F},
                                                                    {new UnitKey{fromUnit=Units.Squareyard,toUnit=Units.Squarekilometre  } ,   0.000001F},
                                                                    {new UnitKey{fromUnit=Units.Squareyard,toUnit=Units.Squareinch  } ,        1296.000062F},
                                                                    {new UnitKey{fromUnit=Units.Squareyard,toUnit=Units.Squaremile  } ,        0F},

                                                                    {new UnitKey{fromUnit=Units.Squaremile,toUnit=Units.Acre  } ,              639.997351F},
                                                                    {new UnitKey{fromUnit=Units.Squaremile,toUnit=Units.Hectare  } ,           258.9988F},
                                                                    {new UnitKey{fromUnit=Units.Squaremile,toUnit=Units.Squarefoot  } ,        27878398.8124F},
                                                                    {new UnitKey{fromUnit=Units.Squaremile,toUnit=Units.Squaremetre  } ,       2589988F},
                                                                    {new UnitKey{fromUnit=Units.Squaremile,toUnit=Units.Squarekilometre  } ,   2.589988F},
                                                                    {new UnitKey{fromUnit=Units.Squaremile,toUnit=Units.Squareinch  } ,        4014489428.9789F},
                                                                    {new UnitKey{fromUnit=Units.Squaremile,toUnit=Units.Squareyard  } ,        3097599.7199F},
                                                                   

                                                                    //***************************LENGTH*******************************************
                                                                    //MILLIMETRE"
                                                                    {new UnitKey{fromUnit=Units.Millimetre,toUnit=Units.Centimetre} ,          0.1f},
                                                                    {new UnitKey{fromUnit=Units.Millimetre,toUnit=Units.Decimetre} ,           0.01f},
                                                                    {new UnitKey{fromUnit=Units.Millimetre,toUnit=Units.Metre} ,               0.001f},
                                                                    {new UnitKey{fromUnit=Units.Millimetre,toUnit=Units.Kilometre} ,           0.000001f},
                                                                    {new UnitKey{fromUnit=Units.Millimetre,toUnit=Units.Feet} ,                0.003281f},
                                                                    {new UnitKey{fromUnit=Units.Millimetre,toUnit=Units.Inch} ,                0.03937f},
                                                                    {new UnitKey{fromUnit=Units.Millimetre,toUnit=Units.Mile} ,                0.000001f},
                                                                    {new UnitKey{fromUnit=Units.Millimetre,toUnit=Units.Yard} ,                0.001094f},

                                                                    {new UnitKey{fromUnit=Units.Centimetre,toUnit=Units.Millimetre} ,          10f},
                                                                    {new UnitKey{fromUnit=Units.Centimetre,toUnit=Units.Decimetre} ,           0.1f},
                                                                    {new UnitKey{fromUnit=Units.Centimetre,toUnit=Units.Metre} ,               0.01f},
                                                                    {new UnitKey{fromUnit=Units.Centimetre,toUnit=Units.Kilometre} ,           0.00001f},
                                                                    {new UnitKey{fromUnit=Units.Centimetre,toUnit=Units.Feet} ,                0.032808f},
                                                                    {new UnitKey{fromUnit=Units.Centimetre,toUnit=Units.Inch} ,                0.393701f},
                                                                    {new UnitKey{fromUnit=Units.Centimetre,toUnit=Units.Mile} ,                0.000006f},
                                                                    {new UnitKey{fromUnit=Units.Centimetre,toUnit=Units.Yard} ,                0.010936f},

                                                                    {new UnitKey{fromUnit=Units.Decimetre,toUnit=Units.Millimetre} ,          100f},
                                                                    {new UnitKey{fromUnit=Units.Decimetre,toUnit=Units.Centimetre} ,          10f},
                                                                    {new UnitKey{fromUnit=Units.Decimetre,toUnit=Units.Metre} ,               0.1f},
                                                                    {new UnitKey{fromUnit=Units.Decimetre,toUnit=Units.Kilometre} ,           0.1f},
                                                                    {new UnitKey{fromUnit=Units.Decimetre,toUnit=Units.Feet} ,                0.328084f},
                                                                    {new UnitKey{fromUnit=Units.Decimetre,toUnit=Units.Inch} ,                3.937008f},
                                                                    {new UnitKey{fromUnit=Units.Decimetre,toUnit=Units.Mile} ,                0.000062f},
                                                                    {new UnitKey{fromUnit=Units.Decimetre,toUnit=Units.Yard} ,                0.109361f},

                                                                    {new UnitKey{fromUnit=Units.Metre,toUnit=Units.Millimetre} ,              1000f},
                                                                    {new UnitKey{fromUnit=Units.Metre,toUnit=Units.Centimetre} ,              100f},
                                                                    {new UnitKey{fromUnit=Units.Metre,toUnit=Units.Decimetre} ,               10f},
                                                                    {new UnitKey{fromUnit=Units.Metre,toUnit=Units.Kilometre} ,               0.001f},
                                                                    {new UnitKey{fromUnit=Units.Metre,toUnit=Units.Feet} ,                    3.28084f},
                                                                    {new UnitKey{fromUnit=Units.Metre,toUnit=Units.Inch} ,                    39.370079f},
                                                                    {new UnitKey{fromUnit=Units.Metre,toUnit=Units.Mile} ,                    0.000621f},
                                                                    {new UnitKey{fromUnit=Units.Metre,toUnit=Units.Yard} ,                    1.093613f},

                                                                    {new UnitKey{fromUnit=Units.Kilometre,toUnit=Units.Millimetre} ,          1000000f},
                                                                    {new UnitKey{fromUnit=Units.Kilometre,toUnit=Units.Centimetre} ,          100000f},
                                                                    {new UnitKey{fromUnit=Units.Kilometre,toUnit=Units.Decimetre} ,           10000f},
                                                                    {new UnitKey{fromUnit=Units.Kilometre,toUnit=Units.Metre} ,               1000f},
                                                                    {new UnitKey{fromUnit=Units.Kilometre,toUnit=Units.Feet} ,                3280.8399f},
                                                                    {new UnitKey{fromUnit=Units.Kilometre,toUnit=Units.Inch} ,                39370.0788f},
                                                                    {new UnitKey{fromUnit=Units.Kilometre,toUnit=Units.Mile} ,                0.621371f},
                                                                    {new UnitKey{fromUnit=Units.Kilometre,toUnit=Units.Yard} ,                1093.613f},

                                                                    {new UnitKey{fromUnit=Units.Feet,toUnit=Units.Millimetre} ,               304.8f},
                                                                    {new UnitKey{fromUnit=Units.Feet,toUnit=Units.Centimetre} ,               30.48f},
                                                                    {new UnitKey{fromUnit=Units.Feet,toUnit=Units.Decimetre} ,                3.048f},
                                                                    {new UnitKey{fromUnit=Units.Feet,toUnit=Units.Metre} ,                    0.3048f},
                                                                    {new UnitKey{fromUnit=Units.Feet,toUnit=Units.Kilometre} ,                0.000305f},
                                                                    {new UnitKey{fromUnit=Units.Feet,toUnit=Units.Inch} ,                     12f},
                                                                    {new UnitKey{fromUnit=Units.Feet,toUnit=Units.Mile} ,                     0.000189f},
                                                                    {new UnitKey{fromUnit=Units.Feet,toUnit=Units.Yard} ,                     0.333333f},

                                                                    {new UnitKey{fromUnit=Units.Inch,toUnit=Units.Millimetre} ,               25.4f},
                                                                    {new UnitKey{fromUnit=Units.Inch,toUnit=Units.Centimetre} ,               2.54f},
                                                                    {new UnitKey{fromUnit=Units.Inch,toUnit=Units.Decimetre} ,                0.254f},
                                                                    {new UnitKey{fromUnit=Units.Inch,toUnit=Units.Metre} ,                    0.0254f},
                                                                    {new UnitKey{fromUnit=Units.Inch,toUnit=Units.Kilometre} ,                0.000025f},
                                                                    {new UnitKey{fromUnit=Units.Inch,toUnit=Units.Feet} ,                     0.083333f},
                                                                    {new UnitKey{fromUnit=Units.Inch,toUnit=Units.Mile} ,                     0.000016f},
                                                                    {new UnitKey{fromUnit=Units.Inch,toUnit=Units.Yard} ,                     0.027778f},

                                                                    {new UnitKey{fromUnit=Units.Mile,toUnit=Units.Millimetre} ,               1609344f},
                                                                    {new UnitKey{fromUnit=Units.Mile,toUnit=Units.Centimetre} ,               160934.4f},
                                                                    {new UnitKey{fromUnit=Units.Mile,toUnit=Units.Decimetre} ,                16093.44f},
                                                                    {new UnitKey{fromUnit=Units.Mile,toUnit=Units.Metre} ,                    1609.344f},
                                                                    {new UnitKey{fromUnit=Units.Mile,toUnit=Units.Kilometre} ,                1.6093f},
                                                                    {new UnitKey{fromUnit=Units.Mile,toUnit=Units.Feet} ,                     5280f},
                                                                    {new UnitKey{fromUnit=Units.Mile,toUnit=Units.Inch} ,                     63360f},
                                                                    {new UnitKey{fromUnit=Units.Mile,toUnit=Units.Yard} ,                     1760f},

                                                                    {new UnitKey{fromUnit=Units.Yard,toUnit=Units.Millimetre} ,               914.4f},
                                                                    {new UnitKey{fromUnit=Units.Yard,toUnit=Units.Centimetre} ,               91.44f},
                                                                    {new UnitKey{fromUnit=Units.Yard,toUnit=Units.Decimetre} ,                9.144f},
                                                                    {new UnitKey{fromUnit=Units.Yard,toUnit=Units.Metre} ,                    0.9144f},
                                                                    {new UnitKey{fromUnit=Units.Yard,toUnit=Units.Kilometre} ,                0.000914f},
                                                                    {new UnitKey{fromUnit=Units.Yard,toUnit=Units.Feet} ,                     3f},
                                                                    {new UnitKey{fromUnit=Units.Yard,toUnit=Units.Inch} ,                     36f},
                                                                    {new UnitKey{fromUnit=Units.Yard,toUnit=Units.Mile} ,                     0.000568f},

                                                                     //**********************TEMPERTURE********************************************
                                                                   {new UnitKey{fromUnit=Units.Celsius,toUnit=Units.Fahrenheit } ,      33.8F},
                                                                   {new UnitKey{fromUnit=Units.Celsius ,toUnit=Units.Kelvin},           274.15f },
                                                                   {new UnitKey{fromUnit=Units.Fahrenheit,toUnit=Units.Celsius } ,      -17.222222f},
                                                                   {new UnitKey{fromUnit=Units.Fahrenheit ,toUnit=Units.Kelvin},        255.9278F },
                                                                   {new UnitKey{fromUnit=Units.Kelvin,toUnit=Units.Celsius } ,          -272.15F},
                                                                   {new UnitKey{fromUnit=Units.Kelvin ,toUnit=Units.Fahrenheit},        -457.87F },
                                                                   
                                                                      //**********************TIME********************************************
                                                                    {new UnitKey{fromUnit=Units.Day,toUnit=Units.Hour} ,                      24f},
                                                                    {new UnitKey{fromUnit=Units.Day,toUnit=Units.Minute} ,                    1440f},
                                                                    {new UnitKey{fromUnit=Units.Day,toUnit=Units.Year} ,                      0.00274f},
                                                                    {new UnitKey{fromUnit=Units.Hour,toUnit=Units.Day} ,                      0.041667f},
                                                                    {new UnitKey{fromUnit=Units.Hour,toUnit=Units.Minute} ,                   60f},
                                                                    {new UnitKey{fromUnit=Units.Hour,toUnit=Units.Year} ,                     0.000114f},
                                                                    {new UnitKey{fromUnit=Units.Minute,toUnit=Units.Day} ,                    0.000694f},
                                                                    {new UnitKey{fromUnit=Units.Minute,toUnit=Units.Hour} ,                   0.016667f},
                                                                    {new UnitKey{fromUnit=Units.Minute,toUnit=Units.Year} ,                   0.000002f},
                                                                    {new UnitKey{fromUnit=Units.Year,toUnit=Units.Day} ,                      365f},
                                                                    {new UnitKey{fromUnit=Units.Year,toUnit=Units.Minute} ,                   525600f},
                                                                    {new UnitKey{fromUnit=Units.Year,toUnit=Units.Hour} ,                     8760f},

                                                                     //***************************VOLUME*******************************************
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.Cubicfoot} ,           0.000035315f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.Cubicinch} ,           0.061024f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.Cubicmile} ,           0f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.Cubicyard} ,           0.0000013080f},                                                                    
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.Cup} ,                 0f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.GallonImp} ,           0f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.GallonUs} ,            0f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.Liter} ,               0.001f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.OunceImpFluid} ,       0.035195f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.OunceUsFluid} ,        0.033814f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.PintImp} ,             0.0017598f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.PintUsLiquid} ,        0.0021134f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.PintUsDry} ,           0.0018162f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.QuartImp} ,            0.00087988f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.QuartUsLiquid} ,       0.0010567f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.QuartUsDry} ,          0.00090808f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.Tablespoon} ,          0f},
                                                                    {new UnitKey{fromUnit=Units.Millilitre,toUnit=Units.Teaspoon} ,            0.20000f},

                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.Millilitre} ,          28317f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.Cubicinch} ,           1728f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.Cubicmile} ,           0f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.Cubicyard} ,           0.037037f},                                                                    
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.Cup} ,                 119.688345f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.GallonImp} ,           6.228836f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.GallonUs} ,            7.48052f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.Liter} ,               28.31685f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.OunceImpFluid} ,       996.6139f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.OunceUsFluid} ,        957.5066f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.PintImp} ,             49.8307f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.PintUsLiquid} ,        59.84416f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.PintUsDry} ,           51.4281f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.QuartImp} ,            24.915335f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.QuartUsLiquid} ,       29.922083f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.QuartUsDry} ,          25.714048f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.Tablespoon} ,          1915.0138f},
                                                                    {new UnitKey{fromUnit=Units.Cubicfoot,toUnit=Units.Teaspoon} ,            5745.0391f},

                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.Millilitre} ,          16.387f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.Cubicfoot} ,           0.000579f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.Cubicmile} ,           0f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.Cubicyard} ,           0.000021f},                                                                    
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.Cup} ,                 0.069264f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.GallonImp} ,           0.003605f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.GallonUs} ,            0.004329f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.Liter} ,               0.016387f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.OunceImpFluid} ,       0.576744f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.OunceUsFluid} ,        0.5541f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.PintImp} ,             0.028837f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.PintUsLiquid} ,        0.034632f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.PintUsDry} ,           0.029762f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.QuartImp} ,            0.014419f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.QuartUsLiquid} ,       0.017316f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.QuartUsDry} ,          0.014881f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.Tablespoon} ,          1.108225f},
                                                                    {new UnitKey{fromUnit=Units.Cubicinch,toUnit=Units.Teaspoon} ,            3.324674f},

                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.Millilitre} ,          0f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.Cubicfoot} ,           147197940448.88f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.Cubicinch} ,           254358133795812.0313f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.Cubicyard} ,           5451775928.7136f},                                                                    
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.Cup} ,                 0f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.GallonImp} ,           916871861313.7958f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.GallonUs} ,            1101117130711.2764f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.Liter} ,               4168182000000.0342f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.OunceImpFluid} ,       146699510717959.7813f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.OunceUsFluid} ,        140942998688355.25f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.PintImp} ,             7334974890510.3662f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.PintUsLiquid} ,        8808937045690.2109f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.PintUsDry} ,           7570109905277.9316f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.QuartImp} ,            3667485928595.0327f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.QuartUsLiquid} ,       4404468988260.125f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.QuartUsDry} ,          3785054952638.9663f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.Tablespoon} ,          281886092693736.5f},
                                                                    {new UnitKey{fromUnit=Units.Cubicmile,toUnit=Units.Teaspoon} ,            845657934939939.25f},

                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.Millilitre} ,           764550f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.Cubicfoot} ,           26.999998f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.Cubicinch} ,           46656.0135f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.Cup} ,                 3231.5851f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.GallonImp} ,           168.1786f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.GallonUs} ,            201.9741f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.Liter} ,               764.5552f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.OunceImpFluid} ,       26908.5836f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.OunceUsFluid} ,        25852.6865f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.PintImp} ,             1345.4291f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.PintUsLiquid} ,        1615.7929f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.PintUsDry} ,           1388.5591f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.QuartImp} ,            672.7143f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.QuartUsLiquid} ,       807.8966f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.QuartUsDry} ,          694.2796f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.Tablespoon} ,          51705.3956f},
                                                                    {new UnitKey{fromUnit=Units.Cubicyard,toUnit=Units.Teaspoon} ,            155116.1239F},

                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.Millilitre} ,          236.59f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.Cubicfoot} ,           0.008355f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.Cubicinch} ,           14.437501f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.Cubicyard} ,           0.000309f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.GallonImp} ,           0.052042f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.GallonUs} ,            0.0625f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.Liter} ,               0.2366f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.OunceImpFluid} ,       8.326741f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.OunceUsFluid} ,        8f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.PintImp} ,             0.4163f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.PintUsLiquid} ,        0.5f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.PintUsDry} ,           0.4297f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.QuartImp} ,            0.2082f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.QuartUsLiquid} ,       0.25f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.QuartUsDry} ,          0.2148f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.Tablespoon} ,          16f},
                                                                    {new UnitKey{fromUnit=Units.Cup,toUnit=Units.Teaspoon} ,            48F},

                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.Millilitre} ,          4546.1f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.Cubicfoot} ,           0.160544f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.Cubicinch} ,           277.419501f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.Cubicyard} ,           0.005946f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.Cup} ,                 19.215f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.GallonUs} ,            1.2009f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.Liter} ,               4.5459f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.OunceImpFluid} ,       159.9933f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.OunceUsFluid} ,        153.721588f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.PintImp} ,             8f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.PintUsLiquid} ,        9.6076f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.PintUsDry} ,           8.256454f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.QuartImp} ,            4f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.QuartUsLiquid} ,       4.8038f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.QuartUsDry} ,          4.1282f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.Tablespoon} ,          307.44328f},
                                                                    {new UnitKey{fromUnit=Units.GallonImp,toUnit=Units.Teaspoon} ,            922.3295F},

                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.Millilitre} ,          3785.4f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.Cubicfoot} ,           0.133681f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.Cubicinch} ,           231.00007f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.Cubicyard} ,           0.004951f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.Cup} ,                 16.000003f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.GallonImp} ,           0.8327f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.Liter} ,               3.7855f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.OunceImpFluid} ,       133.231f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.OunceUsFluid} ,        128.003f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.PintImp} ,             6.661394f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.PintUsLiquid} ,        8f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.PintUsDry} ,           6.874936f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.QuartImp} ,            3.3307f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.QuartUsLiquid} ,       4f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.QuartUsDry} ,          3.4375f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.Tablespoon} ,          256.000097f},
                                                                    {new UnitKey{fromUnit=Units.GallonUs,toUnit=Units.Teaspoon} ,            768F},

                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.Millilitre} ,          1000f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.Cubicfoot} ,           0.035315f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.Cubicinch} ,           61.023759f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.Cubicyard} ,           0.001308f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.Cup} ,                 4.226753f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.GallonImp} ,           0.22f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.GallonUs} ,             0.2642f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.OunceImpFluid} ,       35.1988f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.OunceUsFluid} ,        33.8176f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.PintImp} ,             1.759754f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.PintUsLiquid} ,        2.1134f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.PintUsDry} ,           1.8162f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.QuartImp} ,            0.8799f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.QuartUsLiquid} ,       1.056688f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.QuartUsDry} ,          0.9081f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.Tablespoon} ,          67.628067f},
                                                                    {new UnitKey{fromUnit=Units.Liter,toUnit=Units.Teaspoon} ,            202.8841F},

                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.Millilitre} ,          0F},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.Cubicfoot} ,           0.001003F},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.Cubicinch} ,           1.733872f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.Cubicyard} ,           0.000037f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.Cup} ,                 0.120095f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.GallonImp} ,           0.0062f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.GallonUs} ,            0.007506f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.Liter} ,               0.028413f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.OunceUsFluid} ,        0.96076f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.PintImp} ,             0.05f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.PintUsLiquid} ,        0.06f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.PintUsDry} ,           0.051603f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.QuartImp} ,            0.025f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.QuartUsLiquid} ,       0.030024f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.QuartUsDry} ,          0.025801f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.Tablespoon} ,          1.92152f},
                                                                    {new UnitKey{fromUnit=Units.OunceImpFluid,toUnit=Units.Teaspoon} ,            5.7646F},

                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.Millilitre} ,          0F},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.Cubicfoot} ,           0.001044F},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.Cubicinch} ,           1.804688F},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.Cubicyard} ,           0.000039f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.Cup} ,                 0.125f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.GallonImp} ,           0.006505f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.GallonUs} ,            0.007812f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.Liter} ,               0.029574f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.OunceImpFluid} ,       1.040843f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.PintImp} ,             0.052f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.PintUsLiquid} ,        0.0625f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.PintUsDry} ,           0.0537f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.QuartImp} ,            0.026021f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.QuartUsLiquid} ,       0.03125f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.QuartUsDry} ,          0.0269f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.Tablespoon} ,          2.000001f},
                                                                    {new UnitKey{fromUnit=Units.OunceUsFluid,toUnit=Units.Teaspoon} ,            6F},

                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.Millilitre} ,          568.26F},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.Cubicfoot} ,           0.020068F},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.Cubicinch} ,           34.677438F},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.Cubicyard} ,           0.000743f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.Cup} ,                 2.4019f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.GallonImp} ,           0.125f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.GallonUs} ,            0.150119f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.Liter} ,               0.5683f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.OunceImpFluid} ,       20f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.OunceUsFluid} ,        19.215199f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.PintUsLiquid} ,        1.2009f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.PintUsDry} ,           1.032f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.QuartImp} ,            0.5f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.QuartUsLiquid} ,       0.6005f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.QuartUsDry} ,          0.516f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.Tablespoon} ,          38.4283f},
                                                                    {new UnitKey{fromUnit=Units.PintImp,toUnit=Units.Teaspoon} ,            115.291183F},

                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.Millilitre} ,          473.18F},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.Cubicfoot} ,           0.01671F},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.Cubicinch} ,           28.875009F},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.Cubicyard} ,           0.000619f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.Cup} ,                 2f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.GallonImp} ,           0.1041f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.GallonUs} ,            0.125f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.Liter} ,               0.473177f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.OunceImpFluid} ,       16.653486f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.OunceUsFluid} ,        16f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.PintImp} ,             0.832674f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.PintUsDry} ,           0.859367f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.QuartImp} ,            0.4163f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.QuartUsLiquid} ,       0.5f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.QuartUsDry} ,          0.4297f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.Tablespoon} ,          32.000012f},
                                                                    {new UnitKey{fromUnit=Units.PintUsLiquid,toUnit=Units.Teaspoon} ,            96F},

                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.Millilitre} ,          550.61F},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.Cubicfoot} ,           0.019445F},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.Cubicinch} ,           33.600322F},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.Cubicyard} ,           0.00072f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.Cup} ,                 2.327295f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.GallonImp} ,           0.1211f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.GallonUs} ,            0.1455f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.Liter} ,               0.550611f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.OunceImpFluid} ,       19.378782f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.OunceUsFluid} ,        18.6184f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.PintImp} ,             0.968939f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.PintUsLiquid} ,        1.1636f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.QuartImp} ,            0.484469f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.QuartUsLiquid} ,       0.5818f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.QuartUsDry} ,          0.5f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.Tablespoon} ,          37.2367f},
                                                                    {new UnitKey{fromUnit=Units.PintUsDry,toUnit=Units.Teaspoon} ,            111.7101F},

                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.Millilitre} ,          1136.5F},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.Cubicfoot} ,           0.040136F},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.Cubicinch} ,           69.355f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.Cubicyard} ,           0.001487f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.Cup} ,                 4.8054f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.GallonImp} ,           0.2501f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.GallonUs} ,            0.3004f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.Liter} ,               1.1371f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.OunceImpFluid} ,       40.0203f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.OunceUsFluid} ,        38.4499f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.PintImp} ,             2f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.PintUsLiquid} ,        2.4019f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.PintUsDry} ,           2.0641f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.QuartUsLiquid} ,       1.2009f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.QuartUsDry} ,          1.032f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.Tablespoon} ,          76.8566f},
                                                                    {new UnitKey{fromUnit=Units.QuartImp,toUnit=Units.Teaspoon} ,            230.5697F},
                                                                    
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.Millilitre} ,          946.35F},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.Cubicfoot} ,           0.03342F},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.Cubicinch} ,           57.750011f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.Cubicyard} ,           0.001238f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.Cup} ,                 4.0007f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.GallonImp} ,           0.208169f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.GallonUs} ,            0.25f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.Liter} ,               0.9464f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.OunceImpFluid} ,       33.3086f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.OunceUsFluid} ,        32.0016f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.PintImp} ,             1.6654f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.PintUsLiquid} ,        2.0001f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.PintUsDry} ,           1.7188f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.QuartImp} ,            0.8327f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.QuartUsDry} ,          0.8594f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.Tablespoon} ,          64.0025f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsLiquid,toUnit=Units.Teaspoon} ,            192.0074F},

                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.Millilitre} ,          1101.2F},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.Cubicfoot} ,           0.038889F},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.Cubicinch} ,           67.200645f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.Cubicyard} ,           0.00144f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.Cup} ,                 4.65459f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.GallonImp} ,           0.2422f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.GallonUs} ,            0.2909f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.Liter} ,               1.1012f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.OunceImpFluid} ,       38.7568f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.OunceUsFluid} ,        37.236f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.PintImp} ,             1.9378f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.PintUsLiquid} ,        2.3273f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.PintUsDry} ,           2f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.QuartImp} ,            0.9689f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.QuartUsLiquid} ,       1.1636f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.Tablespoon} ,          74.4704f},
                                                                    {new UnitKey{fromUnit=Units.QuartUsDry,toUnit=Units.Teaspoon} ,            223.4203F},
                                                               
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.Millilitre} ,          14.787F},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.Cubicfoot} ,           0.000522F},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.Cubicinch} ,           0.902f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.Cubicyard} ,           0.000019f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.Cup} ,                 0.0614f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.GallonImp} ,           0.0032f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.GallonUs} ,            0.0038f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.Liter} ,               0.0144f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.OunceImpFluid} ,       0.520421f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.OunceUsFluid} ,        0.5f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.PintImp} ,             0.026f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.PintUsLiquid} ,        0.0312f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.PintUsDry} ,           0.0269f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.QuartImp} ,            0.013f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.QuartUsLiquid} ,       0.0156f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.QuartUsDry} ,          74.4704f},
                                                                    {new UnitKey{fromUnit=Units.Tablespoon,toUnit=Units.Teaspoon} ,            3F},

                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.Millilitre} ,          4.9289F},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.Cubicfoot} ,           0.0005F},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.Cubicinch} ,           0.864f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.Cubicmile} ,           0F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.Cubicyard} ,           0.000006f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.Cup} ,                 0.020833f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.GallonImp} ,           0.001084f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.GallonUs} ,            0.001302f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.Liter} ,               0.004929f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.OunceImpFluid} ,       0.1735f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.OunceUsFluid} ,        0.1667f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.PintImp} ,             0.0087f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.PintUsLiquid} ,        0.0104f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.PintUsDry} ,           0.0089f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.QuartImp} ,            0.004337f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.QuartUsLiquid} ,       0.0052f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.QuartUsDry} ,          0.0045f},
                                                                    {new UnitKey{fromUnit=Units.Teaspoon,toUnit=Units.Tablespoon} ,          0.3351F},
                                                                                                                             
                                                                     //***************************WEIGHT*******************************************
                                                                    {new UnitKey{fromUnit=Units.Milligram,toUnit=Units.Gram  } ,         0.001F},
                                                                    {new UnitKey{fromUnit=Units.Milligram,toUnit=Units.Kilogram } ,      0.000001F},
                                                                    {new UnitKey{fromUnit=Units.Milligram,toUnit=Units.Carat  } ,        0.005F},
                                                                    {new UnitKey{fromUnit=Units.Milligram,toUnit=Units.Ounce  } ,        0.000035F},
                                                                    {new UnitKey{fromUnit=Units.Milligram,toUnit=Units.Pound  } ,        0.000002F},
                                                                    {new UnitKey{fromUnit=Units.Milligram,toUnit=Units.Tonne  } ,        0F},

                                                                    {new UnitKey{fromUnit=Units.Gram,toUnit=Units.Milligram  } ,         1000F},
                                                                    {new UnitKey{fromUnit=Units.Gram,toUnit=Units.Kilogram } ,           0.001F},
                                                                    {new UnitKey{fromUnit=Units.Gram,toUnit=Units.Carat  } ,             5F},
                                                                    {new UnitKey{fromUnit=Units.Gram,toUnit=Units.Ounce  } ,             0.035274F},
                                                                    {new UnitKey{fromUnit=Units.Gram,toUnit=Units.Pound  } ,             0.002205F},
                                                                    {new UnitKey{fromUnit=Units.Gram,toUnit=Units.Tonne  } ,             0.000001F},

                                                                    {new UnitKey{fromUnit=Units.Kilogram,toUnit=Units.Milligram  } ,     1000000F},
                                                                    {new UnitKey{fromUnit=Units.Kilogram,toUnit=Units.Gram } ,           1000F},
                                                                    {new UnitKey{fromUnit=Units.Kilogram,toUnit=Units.Carat  } ,         5000F},
                                                                    {new UnitKey{fromUnit=Units.Kilogram,toUnit=Units.Ounce  } ,         35.273966F},
                                                                    {new UnitKey{fromUnit=Units.Kilogram,toUnit=Units.Pound  } ,         2.204622F},
                                                                    {new UnitKey{fromUnit=Units.Kilogram,toUnit=Units.Tonne  } ,         0.001F},

                                                                    {new UnitKey{fromUnit=Units.Carat,toUnit=Units.Milligram  } ,        200F},
                                                                    {new UnitKey{fromUnit=Units.Carat,toUnit=Units.Gram } ,              0.2F},
                                                                    {new UnitKey{fromUnit=Units.Carat,toUnit=Units.Kilogram  } ,         0.0002F},
                                                                    {new UnitKey{fromUnit=Units.Carat,toUnit=Units.Ounce  } ,            0.007055F},
                                                                    {new UnitKey{fromUnit=Units.Carat,toUnit=Units.Pound  } ,            0.000441F},
                                                                    {new UnitKey{fromUnit=Units.Carat,toUnit=Units.Tonne  } ,            0.0F},

                                                                    {new UnitKey{fromUnit=Units.Pound,toUnit=Units.Milligram  } ,        454000F},
                                                                    {new UnitKey{fromUnit=Units.Pound,toUnit=Units.Gram } ,              454F},
                                                                    {new UnitKey{fromUnit=Units.Pound,toUnit=Units.Kilogram  } ,         0.453592F},
                                                                    {new UnitKey{fromUnit=Units.Pound,toUnit=Units.Carat  } ,            2267.962F},
                                                                    {new UnitKey{fromUnit=Units.Pound,toUnit=Units.Ounce  } ,            16.000003F},
                                                                    {new UnitKey{fromUnit=Units.Pound,toUnit=Units.Tonne  } ,            0.000454F},

                                                                    {new UnitKey{fromUnit=Units.Tonne,toUnit=Units.Milligram  } ,        1000000000F},
                                                                    {new UnitKey{fromUnit=Units.Tonne,toUnit=Units.Gram } ,              1000000F},
                                                                    {new UnitKey{fromUnit=Units.Tonne,toUnit=Units.Kilogram  } ,         1000F},
                                                                    {new UnitKey{fromUnit=Units.Tonne,toUnit=Units.Carat  } ,            5000000F},
                                                                    {new UnitKey{fromUnit=Units.Tonne,toUnit=Units.Ounce  } ,            35273.965838F},
                                                                    {new UnitKey{fromUnit=Units.Tonne,toUnit=Units.Pound  } ,            2204.6225F},

                                                                    {new UnitKey{fromUnit=Units.Ounce,toUnit=Units.Milligram  } ,        28349.52F},
                                                                    {new UnitKey{fromUnit=Units.Ounce,toUnit=Units.Gram  } ,             28.34952F},
                                                                    {new UnitKey{fromUnit=Units.Ounce,toUnit=Units.Kilogram } ,          0.02835F},
                                                                    {new UnitKey{fromUnit=Units.Ounce,toUnit=Units.Carat  } ,            141.7476F},                                                                    
                                                                    {new UnitKey{fromUnit=Units.Ounce,toUnit=Units.Pound  } ,            0.0625F},
                                                                    {new UnitKey{fromUnit=Units.Ounce,toUnit=Units.Tonne  } ,            0.000028F},


                                                               };

        public float convertUnit(Unit unit)
        {
            UnitKey key = new UnitKey();
            key.fromUnit = unit.fromUnit;
            key.toUnit = unit.toUnit;
            float factor = -1f;
            
            if (unitDictionary.ContainsKey(key))
                factor = unitDictionary[key];

            float result = unit.measurement*factor;

            return result;
        }

        

    }
}
